name: CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupération du code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Étape 3 : Construction de l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .

      # Étape 4 : Exécution des tests dans un conteneur
      - name: Run tests
        run: |
          docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest pytest

      # Étape 5 : Push de l'image vers Docker Hub (uniquement sur main)
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest